//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AboutMe.Domain.Entity.AdminEtc
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN_MEMBER
    {
        public int IDX { get; set; }
        public string ADM_ID { get; set; }
        public string ADM_PASS { get; set; }
        public string ADM_NAME { get; set; }
        public string ADM_DEPT { get; set; }
        public string PHONE { get; set; }
        public string MOBILE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> ADM_ROLE_GRADE { get; set; }
        public string MEMO { get; set; }
        public Nullable<System.DateTime> INS_DATE { get; set; }
        public Nullable<int> POINT { get; set; }
        public string ADM_PHOTO { get; set; }
    }
}
