//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AboutMe.Domain.Entity.AdminProduct
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORY
    {
        public int IDX { get; set; }
        public string CATE_GBN { get; set; }
        public string CATE_CODE { get; set; }
        public Nullable<int> RE_SORT { get; set; }
        public string DEPTH1_CODE { get; set; }
        public string DEPTH1_NAME { get; set; }
        public string DEPTH1_IMG { get; set; }
        public string DEPTH2_CODE { get; set; }
        public string DEPTH2_NAME { get; set; }
        public string DEPTH_FLAG { get; set; }
        public string DISPLAY_YN { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
        public Nullable<System.DateTime> INS_DATE { get; set; }
    }
}
